[project]
name = ""
version = ""
description = ""
authors = [
    {name = "QuEra Computing Inc.", email = "info@quera.com"},
]
dependencies = [
    "mkdocs>=1.5.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

